name: nightscout_reporter
description: A web app to generate reports for nightscout data
# version: 1.1.1
# homepage: https://blog.zreptil.de
# author: Andreas.Perlitz <andi@zreptil.de>
# pub global activate webdev 2.6.2

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  angular: ^6.0.1
  angular_components: ^1.0.3
  intl: ^0.16.0
  # crypto: ^2.0.6
  # crypto: ^3.0.0
  dnd: ^2.0.0
  timezone: ^0.7.0
  # googleapis: ^0.55.0
  # googleapis_auth: ^0.2.10
  googleapis: ^1.0.0
  googleapis_auth: ^0.2.12+1
  # googleapis: ^4.0.0
  # googleapis_auth: ^1.1.0
  # js: ^0.6.1+1
  js: ^0.6.3
  dson: any

dev_dependencies:
  build_runner: ^1.9.0
  built_html: ^0.1.0
  build_web_compilers: ^2.12.0
  sass_builder: ^2.1.3
  pedantic: ^1.9.2
